# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags: ['v**']
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: username=${{ github.event.inputs.username }} yarn build --if-present

    - name: Easy Zip Files
      # You may pin to the exact commit or the version.
      # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
      uses: vimtor/action-zip@v1
      with:
        # Files or directories to zip
        files: dist
        # Name of output zip file
        # dest: # optional, default is result.zip
        # Whether to add subdirectories to simply zip all files to the root
        # recursive: # optional, default is true


    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        # name: # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: release.zip
        # The desired behavior if no files are found using the provided path.

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        # Artifact name
        # name: # optional
        # Destination path
        path: ./ # optional
    - run:  ls -R

    - name: Get current time
      uses: srfrnk/current-time@v1.1.0
      with:
        # Time format to use using [MomemtJS syntax](https://momentjs.com/)
        format: YYYYMMDD-hhmmss # optional, default is <None>
      id: current-time
    - name: Commit tagger
      # You may pin to the exact commit or the version.
      # uses: tvdias/github-tagger@ed7350546e3e503b5e942dffd65bc8751a95e49d
      uses: tvdias/github-tagger@v0.0.2
      with:
        # The GITHUB_TOKEN secret
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Tag text
        tag: build-at-${{ steps.current-time.outputs.formattedTime }}
    - name: Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifact/release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: build-at-${{ steps.current-time.outputs.formattedTime }}

    



