
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags: ['v**']
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      savename:
        description: 'A file name passed from the caller workflow'
        default: 'model.onnx'
        required: false
        type: string


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gdown
    - name: download model
      run: gdown --id 1Gh8C-bwl2B90RDrvKJkXafvZC3q4_H_z

    - name: Get current time
      uses: srfrnk/current-time@v1.1.0
      with:
        # Time format to use using [MomemtJS syntax](https://momentjs.com/)
        format: YYYYMMDD-hhmmss # optional, default is <None>
      id: current-time
      
    - name: Commit tagger
      # You may pin to the exact commit or the version.
      # uses: tvdias/github-tagger@ed7350546e3e503b5e942dffd65bc8751a95e49d
      uses: tvdias/github-tagger@v0.0.2
      with:
        # The GITHUB_TOKEN secret
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Tag text
        tag: ${{ github.event.inputs.savename }}-${{ steps.current-time.outputs.formattedTime }}
  
    - name: Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.event.inputs.savename }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.savename }}-${{ steps.current-time.outputs.formattedTime }}

